name: ✨ Feature Request
description: 새로운 기능이나 개선사항을 제안해 주세요.
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
assignees:
  - developjik
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ 기능 요청
        
        새로운 아이디어를 제안해 주셔서 감사합니다! 여러분의 피드백은 프로젝트를 더 좋게 만드는 데 중요합니다.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: "📋 사전 확인사항"
      description: "기능을 요청하기 전에 다음을 확인해 주세요"
      options:
        - label: 기존 이슈에서 동일한 제안이 없는지 확인했습니다
          required: true
        - label: 문서를 확인하여 이미 이 기능이 존재하지 않는지 확인했습니다
          required: true
        - label: 이 기능이 프로젝트의 목표와 일치한다고 생각합니다
          required: true

  - type: textarea
    id: problem-description
    attributes:
      label: "❓ 문제 상황"
      description: "현재 어떤 문제나 불편함이 있나요?"
      placeholder: "현재 상황에서 어떤 어려움을 겪고 있나요? 왜 이 기능이 필요한가요?"
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: "💡 제안하는 해결책"
      description: "어떤 기능이나 개선사항을 원하시나요?"
      placeholder: "구체적으로 어떤 기능을 원하시는지 설명해 주세요."
    validations:
      required: true

  - type: textarea
    id: detailed-description
    attributes:
      label: "📋 상세 설명"
      description: "제안하는 기능에 대해 더 자세히 설명해 주세요."
      placeholder: |
        - 기능의 동작 방식
        - 사용자 인터페이스 (필요한 경우)
        - 예상되는 사용 사례
        - 다른 기능과의 연관성

  - type: dropdown
    id: priority
    attributes:
      label: "🎯 우선순위"
      description: "이 기능의 중요도를 평가해 주세요"
      options:
        - "🔥 높음 - 즉시 필요한 기능"
        - "⚡ 중간 - 중요하지만 급하지 않음"
        - "💭 낮음 - 있으면 좋을 기능"
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: "⚙️ 예상 복잡도"
      description: "이 기능을 구현하는 데 필요한 작업량을 추측해 주세요"
      options:
        - "🟢 간단함 - 며칠 안에 구현 가능"
        - "🟡 보통 - 1-2주 정도 소요"
        - "🟠 복잡함 - 몇 주에서 한 달"
        - "🔴 매우 복잡함 - 한 달 이상"
        - "❓ 잘 모르겠음"

  - type: textarea
    id: alternatives
    attributes:
      label: "🔄 고려한 대안"
      description: "다른 해결 방법이나 대안을 고려해 보셨나요?"
      placeholder: "현재 이 문제를 해결하기 위해 사용하고 있는 방법이나 고려해 본 다른 접근 방식이 있다면 설명해 주세요."

  - type: textarea
    id: use-cases
    attributes:
      label: "🎭 사용 사례"
      description: "이 기능이 어떻게 사용될지 구체적인 예시를 들어주세요."
      placeholder: |
        예시:
        1. 사용자가 X를 하고 싶을 때, Y 기능을 사용하여 Z를 달성한다
        2. 개발자가 A 상황에서 B 기능을 통해 C 문제를 해결한다

  - type: textarea
    id: mockups
    attributes:
      label: "🎨 모크업/스케치"
      description: "UI 관련 기능이라면 간단한 스케치나 모크업을 첨부해 주세요."
      placeholder: "이미지나 간단한 ASCII 아트, 또는 다른 참고 자료를 첨부해 주세요."

  - type: input
    id: related-issues
    attributes:
      label: "🔗 관련 이슈"
      description: "관련된 이슈나 PR이 있다면 번호를 적어주세요."
      placeholder: "예: #123, #456"

  - type: textarea
    id: additional-context
    attributes:
      label: "📝 추가 정보"
      description: "이 기능 요청과 관련된 추가적인 정보가 있다면 공유해 주세요."
      placeholder: "기타 고려사항이나 참고할 만한 자료가 있다면 알려주세요."

  - type: checkboxes
    id: contribution
    attributes:
      label: "🤝 기여 의사"
      description: "이 기능을 구현하는 데 도움을 주실 의향이 있나요?"
      options:
        - label: 이 기능을 구현하는 PR을 작성할 의향이 있습니다
        - label: 기능 설계나 명세 작성을 도울 수 있습니다
        - label: 기능 테스트나 피드백을 제공할 수 있습니다
        - label: 문서 작성을 도울 수 있습니다