name: 🔒 Security Issue
description: 보안 취약점이나 보안 관련 문제를 신고해 주세요.
title: "[Security]: "
labels: ["security", "high-priority"]
assignees:
  - developjik
body:
  - type: markdown
    attributes:
      value: |
        ## 🔒 보안 문제 신고
        
        **⚠️ 중요한 보안 취약점의 경우, 공개적으로 이슈를 생성하지 마세요!**
        
        심각한 보안 문제는 [Security Advisories](https://github.com/developjik/developjik-workspace/security/advisories) 또는 이메일을 통해 비공개로 신고해 주세요.
        
        이 템플릿은 일반적인 보안 개선사항이나 경미한 보안 이슈용입니다.

  - type: checkboxes
    id: security-level
    attributes:
      label: "🔐 보안 수준"
      description: "이 보안 문제의 심각도를 평가해 주세요"
      options:
        - label: 🟢 낮음 - 일반적인 보안 모범사례 개선
        - label: 🟡 보통 - 잠재적 보안 위험
        - label: 🟠 높음 - 실제 보안 취약점 (비공개 신고 고려)
        - label: 🔴 치명적 - 즉시 조치 필요 (비공개 신고 필수)
    validations:
      required: true

  - type: dropdown
    id: security-category
    attributes:
      label: "🏷️ 보안 카테고리"
      description: "어떤 종류의 보안 문제인가요?"
      options:
        - "🔐 인증/인가"
        - "🛡️ XSS (Cross-Site Scripting)"
        - "🔓 CSRF (Cross-Site Request Forgery)"
        - "💉 Injection 공격"
        - "📝 입력 검증"
        - "🗄️ 데이터 노출"
        - "🔒 암호화/해싱"
        - "🌐 HTTPS/TLS"
        - "📦 의존성 취약점"
        - "⚙️ 설정 보안"
        - "📱 클라이언트 보안"
        - "🔗 기타"
    validations:
      required: true

  - type: textarea
    id: security-description
    attributes:
      label: "🔍 보안 문제 설명"
      description: "보안 문제에 대해 설명해 주세요."
      placeholder: |
        보안 문제의 내용을 구체적으로 설명해 주세요.
        (민감한 정보는 포함하지 마세요)
    validations:
      required: true

  - type: textarea
    id: potential-impact
    attributes:
      label: "⚠️ 잠재적 영향"
      description: "이 보안 문제가 미칠 수 있는 영향을 설명해 주세요."
      placeholder: |
        예시:
        - 사용자 데이터 노출 가능성
        - 무단 액세스 허용
        - 시스템 손상 위험
        - 서비스 중단 가능성
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: "🔄 재현 방법"
      description: "보안 문제를 재현하는 방법 (민감한 정보 제외)"
      placeholder: |
        보안 문제를 안전하게 재현할 수 있는 일반적인 단계:
        1. 
        2. 
        3. 
        
        (실제 exploit 코드는 포함하지 마세요)

  - type: textarea
    id: affected-components
    attributes:
      label: "📦 영향받는 구성요소"
      description: "어떤 파일, 모듈, 또는 기능이 영향을 받나요?"
      placeholder: |
        예시:
        - src/auth/login.js
        - 사용자 인증 시스템
        - API 엔드포인트 /api/users
        - 클라이언트 사이드 데이터 처리

  - type: input
    id: affected-versions
    attributes:
      label: "🏷️ 영향받는 버전"
      description: "문제가 있는 버전을 알고 있다면 알려주세요."
      placeholder: "예: v1.2.0 이후, 모든 버전, 확실하지 않음"

  - type: textarea
    id: proposed-solution
    attributes:
      label: "💡 제안하는 해결책"
      description: "이 보안 문제를 해결하기 위한 제안이 있다면 공유해 주세요."
      placeholder: |
        예시:
        - 입력 검증 강화
        - 권한 확인 로직 추가
        - 보안 헤더 설정
        - 라이브러리 업데이트
        - 암호화 적용

  - type: textarea
    id: references
    attributes:
      label: "📚 참고 자료"
      description: "관련된 보안 가이드라인, CVE, 또는 참고 자료가 있다면 공유해 주세요."
      placeholder: |
        예시:
        - OWASP Top 10
        - CVE-2023-XXXX
        - 보안 관련 문서나 블로그
        - 유사한 이슈 사례

  - type: input
    id: reporter-contact
    attributes:
      label: "📧 연락처 (선택사항)"
      description: "추가적인 정보 제공을 위한 연락처 (공개되지 않음)"
      placeholder: "security@example.com (선택사항)"

  - type: checkboxes
    id: security-disclosure
    attributes:
      label: "🤝 공개 정책 동의"
      description: "보안 공개 정책에 대한 이해와 동의"
      options:
        - label: 이 이슈가 수정되기 전까지 세부사항을 공개하지 않겠습니다
          required: true
        - label: 필요시 추가적인 정보를 비공개로 제공할 수 있습니다
        - label: 문제 해결 후 크레딧을 받는 것에 동의합니다 (원하는 경우)

  - type: textarea
    id: additional-notes
    attributes:
      label: "📝 추가 노트"
      description: "기타 중요한 정보가 있다면 공유해 주세요."
      placeholder: |
        - 발견 경위
        - 테스트 환경
        - 임시 완화 방법
        - 기타 고려사항